
import React, { useState, useEffect, useRef } from 'react';
import { 
    Printer, Search, User as UserIcon, Building, CreditCard, 
    Phone, Mail, MapPin, IndianRupee, Globe, Landmark, Download
} from 'lucide-react';
import { User, Role } from '../types';
import { getUsers } from '../services/db';

const AdminTeacherDetailsView = () => {
    const [teachers, setTeachers] = useState<User[]>([]);
    const [searchQuery, setSearchQuery] = useState('');
    const printRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        getUsers().then(users => {
            setTeachers(users.filter(u => u.role === Role.USER));
        }).catch(err => {
            console.error("Failed to load teachers:", err);
            // Error is handled by global response handler but we should avoid stuck loading
        });
    }, []);

    const handlePrint = () => {
        const printContent = printRef.current;
        if (!printContent) return;

        const printWindow = window.open('', '', 'width=1200,height=800');
        if (!printWindow) return;

        printWindow.document.write(`
            <html>
                <head>
                    <title>Teacher Information Report</title>
                    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Syne:wght@700;800&display=swap" rel="stylesheet">
                    <style>
                        body { 
                            font-family: 'DM Sans', sans-serif; 
                            padding: 20px; 
                            color: #1e293b;
                            background: white;
                        }
                        .header { 
                            text-align: center; 
                            margin-bottom: 30px; 
                            border-bottom: 2px solid #e2e8f0;
                            padding-bottom: 20px;
                        }
                        .header h1 { 
                            font-family: 'Syne', sans-serif;
                            margin: 0; 
                            font-size: 24px; 
                            color: #1e293b;
                        }
                        .header p { color: #64748b; margin: 5px 0 0; }
                        table { 
                            width: 100%; 
                            border-collapse: collapse; 
                            margin-top: 20px;
                            font-size: 11px;
                        }
                        th { 
                            background: #f8fafc; 
                            padding: 12px 8px; 
                            text-align: left; 
                            border: 1px solid #e2e8f0;
                            font-weight: 700;
                            text-transform: uppercase;
                            color: #475569;
                        }
                        td { 
                            padding: 10px 8px; 
                            border: 1px solid #e2e8f0; 
                            vertical-align: top;
                        }
                        .footer { 
                            margin-top: 30px; 
                            text-align: right; 
                            font-size: 10px; 
                            color: #94a3b8; 
                        }
                        @media print {
                            .no-print { display: none; }
                            table { page-break-inside: auto; }
                            tr { page-break-inside: avoid; page-break-after: auto; }
                        }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>Teacher Professional Details Report</h1>
                        <p>Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
                    </div>
                    ${printContent.innerHTML}
                    <div class="footer">
                        Generated by Blueprint Admin Portal
                    </div>
                </body>
            </html>
        `);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => {
            printWindow.print();
            printWindow.close();
        }, 500);
    };

    const filteredTeachers = teachers.filter(t => 
        t.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        t.pen?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        t.schoolName?.toLowerCase().includes(searchQuery.toLowerCase())
    );

    return (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
            {/* Action Bar */}
            <div className="flex flex-col md:flex-row justify-between items-center gap-4 border-b border-gray-100 pb-6">
                <div>
                    <h2 className="text-3xl font-bold text-gray-900 font-display tracking-tight">Teacher Details</h2>
                    <p className="text-gray-500 mt-1 font-medium italic">Comprehensive directory of teachers and professional data.</p>
                </div>
                <div className="flex items-center gap-3 w-full md:w-auto">
                    <div className="relative flex-1 md:w-80">
                        <input
                            type="text"
                            placeholder="Search by name, PEN, or school..."
                            className="w-full text-sm border border-gray-100 rounded-2xl p-3.5 pl-11 bg-white shadow-sm focus:ring-4 focus:ring-blue-50 focus:border-blue-200 outline-none transition-all font-medium"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                        />
                        <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                    </div>
                    <button
                        onClick={handlePrint}
                        className="bg-white text-gray-700 border border-gray-200 p-3.5 rounded-2xl font-bold hover:bg-gray-50 transition-all flex items-center gap-2 shadow-sm active:scale-95"
                        title="Print Report"
                    >
                        <Printer size={20} className="text-blue-600" />
                        <span className="hidden sm:inline">Print List</span>
                    </button>
                </div>
            </div>

            {/* Table Container */}
            <div className="ap-card overflow-hidden">
                <div className="overflow-x-auto" ref={printRef}>
                    <table className="w-full text-left border-collapse min-w-[1200px]">
                        <thead>
                            <tr className="bg-gray-50/80 border-b border-gray-100">
                                <th className="p-4 font-black text-[10px] text-gray-400 uppercase tracking-widest items-center gap-1.5 min-w-[200px]">
                                    <UserIcon size={12} className="inline mr-1" /> Teacher & Designation
                                </th>
                                <th className="p-4 font-black text-[10px] text-gray-400 uppercase tracking-widest items-center gap-1.5 min-w-[250px]">
                                    <Building size={12} className="inline mr-1" /> School & Service
                                </th>
                                <th className="p-4 font-black text-[10px] text-gray-400 uppercase tracking-widest items-center gap-1.5 min-w-[130px]">
                                    <CreditCard size={12} className="inline mr-1" /> Professional Info
                                </th>
                                <th className="p-4 font-black text-[10px] text-gray-400 uppercase tracking-widest items-center gap-1.5 min-w-[150px]">
                                    <Phone size={12} className="inline mr-1" /> Contact
                                </th>
                                <th className="p-4 font-black text-[10px] text-gray-400 uppercase tracking-widest items-center gap-1.5 min-w-[300px]">
                                    <Landmark size={12} className="inline mr-1" /> Bank Information
                                </th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-50 bg-white text-gray-800">
                            {filteredTeachers.map(t => (
                                <tr key={t.id} className="hover:bg-blue-50/20 transition-colors group">
                                    <td className="p-4">
                                        <div className="flex items-center gap-3">
                                            <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-slate-100 to-slate-200 flex items-center justify-center text-slate-500 font-bold text-sm">
                                                {t.name.charAt(0)}
                                            </div>
                                            <div>
                                                <div className="font-bold text-gray-900 group-hover:text-blue-600 transition-colors">{t.name}</div>
                                                <div className="flex flex-col gap-1 mt-1">
                                                    <span className="text-[10px] font-bold text-blue-500 uppercase tracking-tight">{t.designation || 'No Designation'}</span>
                                                    <span className="bg-slate-100 text-slate-600 px-2 py-0.5 rounded text-[10px] font-mono font-black inline-block w-fit">
                                                        {t.pen || 'PENDING'}
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td className="p-4">
                                        <div className="space-y-2">
                                            <div>
                                                <div className="text-xs font-bold text-gray-700">{t.schoolName || 'Not Set'}</div>
                                                <div className="text-[10px] text-gray-400 flex items-center gap-1">
                                                    <Globe size={10} /> {t.schoolCode || 'N/A'} • {t.schoolType || '—'}
                                                </div>
                                            </div>
                                            <div className="flex flex-wrap gap-2">
                                                <span className="text-[9px] bg-blue-50 text-blue-600 px-1.5 py-0.5 rounded font-bold">{t.district || '—'}</span>
                                                <span className="text-[9px] bg-slate-50 text-slate-500 px-1.5 py-0.5 rounded font-bold">{t.educationalDistrict || '—'}</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td className="p-4">
                                        <div className="space-y-1.5">
                                            <div className="text-[11px] font-bold text-gray-700 flex items-center gap-1.5">
                                                <IndianRupee size={11} className="text-blue-500" />
                                                {t.basicPay ? t.basicPay.toLocaleString('en-IN') : '—'}
                                            </div>
                                            <div className="grid grid-cols-1 gap-1">
                                                <div className="text-[9px] text-gray-400 flex items-center justify-between">
                                                    <span>Join:</span>
                                                    <span className="font-bold text-gray-600">{t.joinDate || '—'}</span>
                                                </div>
                                                <div className="text-[9px] text-gray-400 flex items-center justify-between">
                                                    <span>Retire:</span>
                                                    <span className="font-bold text-gray-600">{t.retirementDate || '—'}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                    <td className="p-4">
                                        <div className="space-y-1.5">
                                            <div className="text-[11px] font-medium text-gray-600 flex items-center gap-1.5">
                                                <Phone size={12} className="text-gray-300" /> {t.phoneNumber || t.mobile || '—'}
                                            </div>
                                            <div className="text-[11px] font-medium text-gray-400 flex items-center gap-1.5">
                                                <Mail size={12} className="text-gray-300 flex-shrink-0" /> 
                                                <span className="truncate max-w-[120px]">{t.email || '—'}</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td className="p-4">
                                        <div className="grid grid-cols-2 gap-3 bg-gray-50/50 p-3 rounded-xl border border-gray-100">
                                            <div className="space-y-0.5">
                                                <span className="text-[9px] font-black text-gray-400 uppercase block tracking-tighter">Account Number</span>
                                                <span className="text-[11px] font-mono font-bold text-gray-600">{t.bankAccountNumber || t.accountNo || '—'}</span>
                                            </div>
                                            <div className="space-y-0.5">
                                                <span className="text-[9px] font-black text-gray-400 uppercase block tracking-tighter">IFSC Code</span>
                                                <span className="text-[11px] font-mono font-bold text-blue-600">{t.bankIfsc || t.ifscCode || '—'}</span>
                                            </div>
                                            <div className="col-span-2 space-y-0.5 border-t border-gray-100/50 pt-2 mt-0.5">
                                                <span className="text-[9px] font-black text-gray-400 uppercase block tracking-tighter">Bank & Branch</span>
                                                <span className="text-[10px] font-bold text-gray-500">
                                                    {t.bankName || '—'}{t.bankBranch || t.branch ? ` (${t.bankBranch || t.branch})` : ''}
                                                </span>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                {filteredTeachers.length === 0 && (
                    <div className="py-24 text-center">
                        <div className="w-16 h-16 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-4 text-gray-300">
                            <Search size={32} />
                        </div>
                        <h3 className="font-bold text-gray-900">No teachers found</h3>
                        <p className="text-gray-500 text-sm mt-1">Try adjusting your search criteria.</p>
                    </div>
                )}
            </div>
            
            <div className="flex flex-col sm:flex-row justify-between items-center gap-4 text-[11px] text-gray-400 font-medium bg-white p-4 rounded-2xl border border-gray-100 shadow-sm">
                <div className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-green-500"></span>
                    <span>Showing {filteredTeachers.length} of {teachers.length} registered teachers</span>
                </div>
                <p className="uppercase tracking-widest font-black opacity-50">Confidential Administration Data</p>
            </div>
        </div>
    );
};

export default AdminTeacherDetailsView;
