
import React, { useState, useEffect, useRef } from 'react';
import { 
    Printer, Search, User as UserIcon, Building, CreditCard, 
    Phone, Mail, MapPin, IndianRupee, Globe, Landmark, Download
} from 'lucide-react';
import { User, Role } from '../types';
import { getUsers } from '../services/db';

const AdminTeacherDetailsView = () => {
    const [teachers, setTeachers] = useState<User[]>([]);
    const [searchQuery, setSearchQuery] = useState('');
    const printRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        getUsers().then(users => {
            setTeachers(users.filter(u => u.role === Role.USER));
        }).catch(err => {
            console.error("Failed to load teachers:", err);
            // Error is handled by global response handler but we should avoid stuck loading
        });
    }, []);

    const handlePrint = () => {
        const printContent = printRef.current;
        if (!printContent) return;

        const printWindow = window.open('', '', 'width=1200,height=800');
        if (!printWindow) return;

        printWindow.document.write(`
            <html>
                <head>
                    <title>Teacher Information Report</title>
                    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Syne:wght@700;800&display=swap" rel="stylesheet">
                    <style>
                        body { 
                            font-family: 'DM Sans', sans-serif; 
                            padding: 20px; 
                            color: #1e293b;
                            background: white;
                        }
                        .header { 
                            text-align: center; 
                            margin-bottom: 30px; 
                            border-bottom: 2px solid #e2e8f0;
                            padding-bottom: 20px;
                        }
                        .header h1 { 
                            font-family: 'Syne', sans-serif;
                            margin: 0; 
                            font-size: 24px; 
                            color: #1e293b;
                        }
                        .header p { color: #64748b; margin: 5px 0 0; }
                        table { 
                            width: 100%; 
                            border-collapse: collapse; 
                            margin-top: 10px;
                            font-size: 10px;
                        }
                        th { 
                            background: #f1f5f9; 
                            padding: 6px 4px; 
                            text-align: left; 
                            border: 1px solid #cbd5e1;
                            font-weight: 800;
                            text-transform: uppercase;
                            color: #334155;
                            font-size: 8px;
                        }
                        td { 
                            padding: 6px 4px; 
                            border: 1px solid #cbd5e1; 
                            vertical-align: middle;
                        }
                        .teacher-name { font-size: 12px; font-weight: bold; color: #000; }
                        .pen-no { font-size: 9px; color: #2563eb; font-weight: bold; }
                        .school-name { font-weight: bold; color: #334155; }
                        .sub-info { font-size: 8px; color: #64748b; }
                        .footer { 
                            margin-top: 20px; 
                            text-align: right; 
                            font-size: 8px; 
                            color: #94a3b8; 
                        }
                        @media print {
                            .no-print { display: none; }
                            table { page-break-inside: auto; }
                            tr { page-break-inside: avoid; page-break-after: auto; }
                        }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>Teacher Professional Details Report</h1>
                        <p>Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}</p>
                    </div>
                    ${printContent.innerHTML}
                    <div class="footer">
                        Generated by Blueprint Admin Portal
                    </div>
                </body>
            </html>
        `);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => {
            printWindow.print();
            printWindow.close();
        }, 500);
    };

    const filteredTeachers = teachers.filter(t => 
        t.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        t.pen?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        t.schoolName?.toLowerCase().includes(searchQuery.toLowerCase())
    );

    return (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-700">
            {/* Header Section */}
            <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4 border-b border-gray-100 pb-6">
                {/* Left Side: Title and Subtitle */}
                <div className="space-y-1">
                    <h2 className="text-3xl font-bold text-gray-900 font-display tracking-tight">
                        Teacher Details
                    </h2>
                    <p className="text-gray-500 font-medium italic">
                        Comprehensive directory of teachers and professional data.
                    </p>
                </div>

                {/* Right Side: Search Bar and Print Button */}
                <div className="flex flex-col sm:flex-row items-center gap-3 w-full lg:w-auto">
                    <div className="relative flex-1 w-full lg:w-80">
                        <input
                            type="text"
                            placeholder="Search by name, PEN, or school..."
                            className="w-full text-sm border border-gray-100 rounded-2xl p-3.5 pl-11 bg-white shadow-sm focus:ring-4 focus:ring-blue-50 focus:border-blue-200 outline-none transition-all font-medium"
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                        />
                        <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                    </div>
                    <button
                        onClick={handlePrint}
                        className="w-full sm:w-auto bg-white text-gray-700 border border-gray-200 p-3.5 rounded-2xl font-bold hover:bg-gray-50 transition-all flex items-center justify-center gap-2 shadow-sm active:scale-95 whitespace-nowrap"
                        title="Print Report"
                    >
                        <Printer size={20} className="text-blue-600" />
                        <span>Print List</span>
                    </button>
                </div>
            </div>

            {/* Table Container */}
            <div className="ap-card overflow-hidden">
                <div className="overflow-x-auto scrollbar-hide" ref={printRef}>
                    <table className="w-full text-left border-collapse min-w-[1000px] text-[11px]">
                        <thead>
                            <tr className="bg-gray-50/80 border-b border-gray-100">
                                <th className="p-2 font-black text-[9px] text-gray-400 uppercase tracking-widest border-x border-gray-100">
                                    Teacher Name (PEN)
                                </th>
                                <th className="p-2 font-black text-[9px] text-gray-400 uppercase tracking-widest border-x border-gray-100">
                                    School Name (Code)
                                </th>
                                <th className="p-2 font-black text-[9px] text-gray-400 uppercase tracking-widest border-x border-gray-100">
                                    Mobile & Email
                                </th>
                                <th className="p-2 font-black text-[9px] text-gray-400 uppercase tracking-widest border-x border-gray-100">
                                    Basic Pay
                                </th>
                                <th className="p-2 font-black text-[9px] text-gray-400 uppercase tracking-widest border-x border-gray-100">
                                    Account No & Bank
                                </th>
                                <th className="p-2 font-black text-[9px] text-gray-400 uppercase tracking-widest border-x border-gray-100">
                                    IFSC & Branch
                                </th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-50 bg-white text-gray-800">
                            {filteredTeachers.map(t => (
                                <tr key={t.id} className="hover:bg-blue-50/20 transition-colors group">
                                    <td className="p-2 border-x border-gray-50">
                                        <div className="font-bold text-sm text-gray-900 leading-tight">{t.name}</div>
                                        <div className="text-[10px] font-black text-blue-600">({t.pen || 'PENDING'})</div>
                                    </td>
                                    <td className="p-2 border-x border-gray-50">
                                        <div className="font-bold text-gray-800 leading-tight">{t.schoolName || 'Not Set'}</div>
                                        <div className="text-[10px] text-gray-400 font-bold uppercase tracking-wider">({t.schoolCode || 'N/A'})</div>
                                    </td>
                                    <td className="p-2 border-x border-gray-50">
                                        <div className="font-bold text-gray-700">{t.phoneNumber || t.mobile || '—'}</div>
                                        <div className="text-[10px] text-gray-400 font-medium lowercase truncate max-w-[150px]">{t.email || '—'}</div>
                                    </td>
                                    <td className="p-2 border-x border-gray-50 font-bold text-gray-900">
                                        {t.basicPay ? `₹${t.basicPay.toLocaleString('en-IN')}` : '—'}
                                    </td>
                                    <td className="p-2 border-x border-gray-50">
                                        <div className="font-mono font-bold text-gray-700">{t.bankAccountNumber || t.accountNo || '—'}</div>
                                        <div className="text-[10px] text-gray-400 font-black uppercase tracking-widest">{t.bankName || '—'}</div>
                                    </td>
                                    <td className="p-2 border-x border-gray-50">
                                        <div className="font-mono font-bold text-blue-600">{t.bankIfsc || t.ifscCode || '—'}</div>
                                        <div className="text-[10px] text-gray-400 font-black uppercase tracking-widest">{t.bankBranch || t.branch || '—'}</div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>

                {filteredTeachers.length === 0 && (
                    <div className="py-24 text-center">
                        <div className="w-16 h-16 bg-gray-50 rounded-full flex items-center justify-center mx-auto mb-4 text-gray-300">
                            <Search size={32} />
                        </div>
                        <h3 className="font-bold text-gray-900">No teachers found</h3>
                        <p className="text-gray-500 text-sm mt-1">Try adjusting your search criteria.</p>
                    </div>
                )}
            </div>

            <style dangerouslySetInnerHTML={{ __html: `
                .scrollbar-hide::-webkit-scrollbar {
                    display: none;
                }
                .scrollbar-hide {
                    -ms-overflow-style: none;
                    scrollbar-width: none;
                }
            ` }} />
            
            <div className="flex flex-col sm:flex-row justify-between items-center gap-4 text-[11px] text-gray-400 font-medium bg-white p-4 rounded-2xl border border-gray-100 shadow-sm">
                <div className="flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-green-500"></span>
                    <span>Showing {filteredTeachers.length} of {teachers.length} registered teachers</span>
                </div>
                <p className="uppercase tracking-widest font-black opacity-50">Confidential Administration Data</p>
            </div>
        </div>
    );
};

export default AdminTeacherDetailsView;
