import React, { useState } from 'react';
import { Bold, Italic, Underline, List, ListOrdered, Image, Table as TableIcon, Plus, Trash2 } from 'lucide-react';
import SimpleRichTextEditor from './SimpleRichTextEditor';
import { Discourse, DiscourseScores, BlueprintItem, Unit, SubUnit } from '../types';

export const QuestionRow = ({ item, index, onUpdateItem, availableDiscourses, systemSettings, curriculum, section, sectionItems }: any) => {
    const [activeTab, setActiveTab] = useState<'question' | 'answer'>('question');
    const [answerMode, setAnswerMode] = useState<'content' | 'discourse' | 'ai'>('content');
    const [isGenerating, setIsGenerating] = useState(false);

    // Helpers for Unit selection
    const selectedUnit = curriculum?.units.find((u: Unit) => u.id === item.unitId);
    const availableSubUnits = selectedUnit?.subUnits || [];

    const sectionOptionCount = section?.optionCount || 0;
    const currentSectionOptionUsage = sectionItems?.filter((si: any) => si.hasInternalChoice).length || 0;

    // Limits based on mark rules: 1 & 2 marks have no option.
    const isMarkRestricted = item.marksPerQuestion <= 2;
    // Can't enable if we hit the limit, UNLESS it's already enabled
    const isLimitReached = !item.hasInternalChoice && currentSectionOptionUsage >= sectionOptionCount;
    const canToggleOption = !isMarkRestricted && (item.hasInternalChoice || !isLimitReached);

    const generateAIAnswer = (targetField: 'answerText' | 'answerTextB', sourceField: 'questionText' | 'questionTextB') => {
        setIsGenerating(true);
        setTimeout(() => {
            onUpdateItem(item.id, targetField, `<p>Answer generated by AI based on: "${item[sourceField] || 'question'}"</p>`);
            setIsGenerating(false);
            setAnswerMode('content');
        }, 1500);
    };

    const applyDiscourse = (discourseId: string, targetField: 'answerText' | 'answerTextB') => {
        const d = availableDiscourses.find((x: Discourse) => x.id === discourseId);
        if (d) {
            let html = `<p><b>${d.name}</b></p>`;
            if (d.description) html += `<p>${d.description}</p>`;
            html += `<ul class="list-disc pl-4">`;
            d.rubrics.forEach((r: DiscourseScores) => {
                html += `<li>${r.point} - <b>${r.marks}M</b></li>`;
            });
            html += `</ul>`;
            onUpdateItem(item.id, targetField, html);

            // Apply Cognitive Process if present in Discourse (only for main/A option or global)
            if (d.cognitiveProcess && targetField === 'answerText') {
                onUpdateItem(item.id, 'cognitiveProcess', d.cognitiveProcess);
            }
        }
    };

    return (
        <div className="border rounded-lg bg-white shadow-sm hover:shadow-md transition-shadow">
            {/* Header / Metadata Row */}
            <div className="bg-gray-50 p-3 border-b flex flex-wrap gap-4 items-center justify-between rounded-t-lg">
                <div className="flex items-center gap-3">
                    <span className="w-8 h-8 rounded-full bg-blue-600 text-white flex items-center justify-center font-bold text-sm">
                        Q{index + 1}
                    </span>
                    <span className="font-bold text-gray-700 text-sm">
                        {item.marksPerQuestion} Mark{item.marksPerQuestion > 1 ? 's' : ''}
                    </span>

                    {/* Internal Choice Toggle */}
                    <div className="flex items-center gap-2 ml-4 border-l pl-4">
                        <span className="tamil-font font-bold text-gray-500 uppercase tracking-widest text-[10px]">உள்நிலைத் தெரிவு (அ/ஆ)</span>
                        <button
                            onClick={() => canToggleOption && onUpdateItem(item.id, 'hasInternalChoice', !item.hasInternalChoice)}
                            disabled={!canToggleOption}
                            className={`w-10 h-5 rounded-full p-1 transition-all ${item.hasInternalChoice ? 'bg-blue-600 shadow-inner' : 'bg-gray-300'} ${!canToggleOption ? 'opacity-30 cursor-not-allowed grayscale' : 'hover:scale-105 active:scale-95'}`}
                            title={isMarkRestricted ? "1, 2 மதிப்பெண்ணிற்கு ஆப்ஷன் இல்லை" : isLimitReached ? `Limit of ${sectionOptionCount} options reached for this section` : "Enable Internal Choice (Either/Or)"}
                        >
                            <div className={`w-3 h-3 bg-white rounded-full shadow-sm transform transition-transform ${item.hasInternalChoice ? 'translate-x-5' : 'translate-x-0'}`} />
                        </button>
                        {sectionOptionCount > 0 && !isMarkRestricted && (
                            <span className="text-[10px] font-medium text-gray-400">
                                ({currentSectionOptionUsage}/{sectionOptionCount} used)
                            </span>
                        )}
                    </div>
                </div>

                <div className="flex flex-wrap gap-2 items-center">
                    {curriculum && (
                        <>
                            <select
                                className="border rounded px-2 py-1 text-xs bg-white focus:ring-2 focus:ring-blue-100 outline-none max-w-[250px]"
                                value={item.unitId}
                                onChange={(e) => {
                                    onUpdateItem(item.id, 'unitId', e.target.value);
                                    // Reset subunit when unit changes
                                    const newUnit = curriculum.units.find((u: Unit) => u.id === e.target.value);
                                    if (newUnit && newUnit.subUnits.length > 0) {
                                        onUpdateItem(item.id, 'subUnitId', newUnit.subUnits[0].id);
                                    } else {
                                        onUpdateItem(item.id, 'subUnitId', '');
                                    }
                                }}
                                title="Unit"
                            >
                                {curriculum.units.map((u: Unit) => <option key={u.id} value={u.id}>Unit {u.unitNumber}: {u.name}</option>)}
                            </select>

                            <select
                                className="border rounded px-2 py-1 text-xs bg-white focus:ring-2 focus:ring-blue-100 outline-none max-w-[250px]"
                                value={item.subUnitId}
                                onChange={(e) => onUpdateItem(item.id, 'subUnitId', e.target.value)}
                                title="Sub-Unit"
                                disabled={!item.unitId || availableSubUnits.length === 0}
                            >
                                {availableSubUnits.length === 0 && <option value="">No Subunits</option>}
                                {availableSubUnits.map((s: SubUnit) => <option key={s.id} value={s.id}>{s.name}</option>)}
                            </select>
                        </>
                    )}

                    <select
                        className={`border rounded px-2 py-1 text-xs bg-white focus:ring-2 focus:ring-blue-100 outline-none ${item.marksPerQuestion === 1 ? 'opacity-75 bg-gray-50' : ''}`}
                        value={item.knowledgeLevel}
                        onChange={(e) => onUpdateItem(item.id, 'knowledgeLevel', e.target.value)}
                        title="Knowledge Level"
                        disabled={item.marksPerQuestion === 1}
                    >
                        {systemSettings.knowledgeLevels.map((k: any) => <option key={k.code} value={k.name}>{k.name}</option>)}
                    </select>

                    <select
                        className="border rounded px-2 py-1 text-xs bg-white focus:ring-2 focus:ring-blue-100 outline-none"
                        value={item.cognitiveProcess}
                        onChange={(e) => onUpdateItem(item.id, 'cognitiveProcess', e.target.value)}
                        title="Cognitive Process"
                    >
                        {systemSettings.cognitiveProcesses.map((c: any) => <option key={c.code} value={c.description}>{c.name}</option>)}
                    </select>

                    <select
                        className="border rounded px-2 py-1 text-xs bg-white focus:ring-2 focus:ring-blue-100 outline-none w-24"
                        value={item.itemFormat}
                        onChange={(e) => onUpdateItem(item.id, 'itemFormat', e.target.value)}
                        title="Item Format"
                    >
                        {systemSettings.itemFormats.map((f: any) => <option key={f.code} value={f.name}>{f.name}</option>)}
                    </select>
                </div>
            </div>

            {/* Content Area */}
            <div className="p-4">
                {/* Tabs */}
                <div className="flex border-b mb-4">
                    <button
                        onClick={() => setActiveTab('question')}
                        className={`px-4 py-2 text-sm font-medium mr-1 rounded-t-md transition-colors ${activeTab === 'question' ? 'bg-blue-50 text-blue-700 border-b-2 border-blue-600' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        Question
                    </button>
                    <button
                        onClick={() => setActiveTab('answer')}
                        className={`px-4 py-2 text-sm font-medium rounded-t-md transition-colors ${activeTab === 'answer' ? 'bg-green-50 text-green-700 border-b-2 border-green-600' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        Answer
                    </button>
                </div>

                {/* Tab Content */}
                <div className="min-h-[150px]">
                    {activeTab === 'question' && (
                        <div className="animate-fade-in space-y-6">
                            {/* Option A (Default) */}
                            <div>
                                {item.hasInternalChoice && <div className="tamil-font font-bold text-red-600 mb-1">ஏதேனும் ஒன்றிற்கு விடையளிக்கவும்</div>}
                                {item.hasInternalChoice && <div className="tamil-font font-bold text-blue-600 mb-1">(அ) வினா</div>}
                                <SimpleRichTextEditor
                                    value={item.questionText}
                                    onChange={(val: string) => onUpdateItem(item.id, 'questionText', val)}
                                    placeholder="Type the question content here..."
                                />
                            </div>

                            {item.hasInternalChoice && (
                                <div className="tamil-font font-bold text-purple-600 flex items-center gap-2">
                                    <span className="bg-purple-600 text-white px-1.5 py-0.5 rounded text-[10px]">அல்லது</span>
                                </div>
                            )}

                            {/* Option B (If Enabled) */}
                            {item.hasInternalChoice && (
                                <div className="border-t pt-1 bg-purple-50/20 p-4 rounded-lg border border-purple-100">
                                    <div className="flex justify-between items-center mb-3">
                                        <div className="tamil-font font-bold text-blue-600 mb-1"> (ஆ) வினா </div>
                                    </div>
                                    <SimpleRichTextEditor
                                        value={item.questionTextB}
                                        onChange={(val: string) => onUpdateItem(item.id, 'questionTextB', val)}
                                        placeholder="Type the second option (ஆ) வினா content here..."
                                    />
                                </div>
                            )}
                        </div>
                    )}

                    {activeTab === 'answer' && (
                        <div className="animate-fade-in space-y-6">
                            {/* Option A Answer */}
                            <div className="space-y-3">
                                {item.hasInternalChoice && <div className="tamil-font font-bold text-blue-600">(அ) வினாவிற்கான விடை</div>}

                                <div className="flex items-center gap-2 mb-2 bg-gray-50 p-2 rounded border border-gray-100">
                                    <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">Mode:</span>
                                    <select
                                        className="border rounded px-2 py-1 text-sm bg-white"
                                        value={answerMode}
                                        onChange={(e) => setAnswerMode(e.target.value as any)}
                                    >
                                        <option value="content">Write Content</option>
                                        <option value="discourse">Select Discourse</option>
                                        <option value="ai">AI Generation</option>
                                    </select>
                                </div>

                                {answerMode === 'content' && (
                                    <SimpleRichTextEditor
                                        value={item.answerText}
                                        onChange={(val: string) => onUpdateItem(item.id, 'answerText', val)}
                                        placeholder="Type the answer key or hints..."
                                        isAnswerTab={true}
                                    />
                                )}
                                {answerMode === 'discourse' && (
                                    <div className="border rounded p-4 bg-gray-50">
                                        <p className="text-sm text-gray-600 mb-2">Select a discourse rubrics to apply:</p>
                                        {availableDiscourses.length === 0 ? (
                                            <p className="text-red-500 text-sm italic">No discourses found for {item.marksPerQuestion} Marks.</p>
                                        ) : (
                                            <select
                                                className="w-full border p-2 rounded mb-2"
                                                onChange={(e) => {
                                                    if (e.target.value) {
                                                        applyDiscourse(e.target.value, 'answerText');
                                                        setAnswerMode('content');
                                                    }
                                                }}
                                                defaultValue=""
                                            >
                                                <option value="" disabled>-- Choose Discourse --</option>
                                                {availableDiscourses.map((d: Discourse) => (
                                                    <option key={d.id} value={d.id}>{d.name} ({d.cognitiveProcess ? d.cognitiveProcess : 'No CP'})</option>
                                                ))}
                                            </select>
                                        )}
                                    </div>
                                )}
                                {answerMode === 'ai' && (
                                    <div className="border rounded p-6 bg-blue-50 text-center">
                                        <button
                                            onClick={() => generateAIAnswer('answerText', 'questionText')}
                                            disabled={isGenerating || !item.questionText}
                                            className="bg-blue-600 text-white px-4 py-2 rounded shadow hover:bg-blue-700 disabled:bg-gray-400 transition"
                                        >
                                            {isGenerating ? 'Generating...' : 'Generate Answer with AI'}
                                        </button>
                                    </div>
                                )}
                            </div>

                            {/* Option B Answer */}
                            {item.hasInternalChoice && (
                                <div className="space-y-3 pt-4 border-t">
                                    <div className="tamil-font font-bold text-purple-600">(ஆ) வினாவிற்கான விடை</div>
                                    <div className="flex items-center gap-2 mb-2 bg-gray-50 p-2 rounded border border-gray-100">
                                        <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">Mode:</span>
                                        <select className="border rounded px-2 py-1 text-sm bg-white" value={answerMode} onChange={(e) => setAnswerMode(e.target.value as any)}>
                                            <option value="content">Write Content</option>
                                            <option value="discourse">Select Discourse</option>
                                            <option value="ai">AI Generation</option>
                                        </select>
                                    </div>
                                    {answerMode === 'content' && <SimpleRichTextEditor value={item.answerTextB} onChange={(val: string) => onUpdateItem(item.id, 'answerTextB', val)} placeholder="Type the answer key or hints for (ஆ)..." isAnswerTab={true} />}
                                    {answerMode === 'discourse' && (
                                        <div className="border rounded p-4 bg-gray-50">
                                            <select className="w-full border p-2 rounded mb-2" onChange={(e) => { if (e.target.value) { applyDiscourse(e.target.value, 'answerTextB'); setAnswerMode('content'); } }} defaultValue="">
                                                <option value="" disabled>-- Choose Discourse --</option>
                                                {availableDiscourses.map((d: Discourse) => <option key={d.id} value={d.id}>{d.name}</option>)}
                                            </select>
                                        </div>
                                    )}
                                    {answerMode === 'ai' && (
                                        <div className="border rounded p-6 bg-blue-50 text-center">
                                            <button onClick={() => generateAIAnswer('answerTextB', 'questionTextB')} disabled={isGenerating || !item.questionTextB} className="bg-blue-600 text-white px-4 py-2 rounded shadow hover:bg-blue-700 disabled:bg-gray-400 transition">
                                                {isGenerating ? 'Generating...' : 'Generate Answer (ஆ) with AI'}
                                            </button>
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default QuestionRow;
